#:schema https://json.schemastore.org/pyproject.json
[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[project]
name = "hidden"
version = "0.4.0"
description = "idk"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "MMDam", email = "amirmohammadghasemi89@gmail.com" },
  { name = "havinaccount", email = "203082879+havinaccount@users.noreply.github.com" },
]
dependencies = []

[project.scripts]
projects = "projects:hidden"

[tool.ruff]
line-length = 100


# cSpell: words pylint
[tool.pylint.messages_control]
disable = ["fixme", "unused-argument"]

[dependency-groups]
dev = ["pytest>=9.1.1", "ruff>=0.16.2"]
